source "https://rubygems.org"

ruby "3.2.2"

gem "rails", "~> 7.1"
gem "pg", "~> 1.5"
gem "devise", "~> 4.9"
gem "faraday", "~> 2.9"
gem "stripe", "~> 10.0"
gem "sentry-ruby", "~> 5.16"

group :development, :test do
  gem "rspec-rails"
end
